---
title: "Ciccolini_Week1_Trial"
author: "Skylar Ciccolini"
date: "2025-08-25"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

We are going to import data from journey north monarch data.

```{r}
jn <- read.csv("Data/journeynorth.csv")

jn2 <- read.csv("Data/journeynorth2.csv")

```


## Check out the data

```{r}

head(jn) ##look at first 6 records

head(jn, 10) ##look at first 10 records

head(jn2)

str(jn)

str(jn2)

```

## Merge the datasets

```{r}

#one way to do this is with rbind
jn_full <- rbind(jn, jn2)

#check df
head(jn_full)

#indexing into df

dim(jn_full) ##gives you rows/col dimensions

ncol(jn_full) ##just gives you cols

nrow(jn_full) ##just gives you rows

length(jn_full) ##defaults to length of no of cols

length(jn_full[ , 1]) ##gives all rows and first col

length(jn_full[1, ]) ##gives first row, all cols

length(jn_full$Date) ##can also index by col name

#extracting column names
jn_names <- names(jn_full) ##gives you a vector of col names

jn_names

```

## Replace Column Names

```{r}

#replace the names 
names(jn_full) <- c("Date", "Town", "State", "Lat", "Long", "Count")

head(jn_full)

# Another way
Newnames <- c("Date", "Town", "State", "Lat", "Long", "Count")

names(jn_full) <- Newnames


```

## Create a subset

```{r}

#pull out state and location
jn_sub <- jn_full[ , c("State", "Count")]

head(jn_sub)

# OR

jn_sub <- jn_full$State

jn_sub2 <- jn_full$Count

jn_sub_forreal <- cbind(jn_sub, jn_sub2)

head(jn_sub_forreal)


```

## Filter to Specific Rows

```{r}
# filter to MO specific records
jn_MO <- jn_full[jn_full$State == "MO" ,]

head(jn_MO)

# filter to cities named columbia

jn_CO <- jn_full[jn_full$Town == "Columbia", ]

head(jn_CO)

# filter to Columbia, MO

jn_COMO <- jn_full[jn_full$State == "MO" & jn_full$Town == "Columbia", ]

head(jn_COMO)

# remove cols

jn_COMO <- jn_full[jn_full$State == "MO" & jn_full$Town == "Columbia", c("Town", "State", "Count")]

head(jn_COMO)

```

## Calculate a Percentage of Total Sightings

```{r}

perc_como <- nrow(jn_full[jn_full$Town == "Columbia" & jn_full$State == "MO" , ]) / nrow(jn_full) * 100


perc_como

```















